workflows:
  react-native-android:
    name: React Native Android APK Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Generate Android folder if missing
        script: |
          if [ ! -d "android" ]; then
            npx expo prebuild --platform android --clean
          fi
      - name: Fix execution permissions
        script: |
          cd android && chmod +x gradlew
      - name: Build Android APK Release
        script: |
          # Questo comando compila l'app definitiva includendo tutto il codice al suo interno
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
