import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import dataset from "@/shared/players.json";
import { createListoneImportUpdate } from "@/lib/auction-utils";
export type Role = "P" | "D" | "C" | "A";
export type Tier = "TOP" | "SEMITOP" | "1° FASCIA" | "2° FASCIA" | "3° FASCIA" | "4° FASCIA" | "5° FASCIA" | "6° FASCIA";
export type ListPlayer = { name: string; team: string; role: Role; price: number; fvm: number };
export type ListoneMeta = { source: string; season: string; updatedAt: string; fileName?: string; sheetName?: string };
export type Purchase = { player: string; team: string; role: Role; owner: string; amount: number };
export type RosterSlots = Record<Role, number>;
export type StrategyBudgets = Record<Role, string>;
export type TierColors = Record<Tier, string>;
export type StrategySlot = { id: number; role: Role; player: string; tier: string; budget: string };
const defaultSlots: RosterSlots = { P: 3, D: 8, C: 8, A: 6 };
const defaultParticipants = ["Io"];
const defaultStrategyBudgets: StrategyBudgets = { P: "", D: "", C: "", A: "" };
const defaultPlayers = dataset.players as ListPlayer[];
const defaultListoneMeta: ListoneMeta = { source: dataset.source, season: dataset.season, updatedAt: dataset.updatedAt };
const defaultTierLabels: Record<Tier, string> = { TOP: "TOP", SEMITOP: "SEMITOP", "1° FASCIA": "1° fascia", "2° FASCIA": "2° fascia", "3° FASCIA": "3° fascia", "4° FASCIA": "4° fascia", "5° FASCIA": "5° fascia", "6° FASCIA": "6° fascia" };
const defaultTierColors: TierColors = { TOP: "#FDE68A", SEMITOP: "#E9D5FF", "1° FASCIA": "#D9F99D", "2° FASCIA": "#A7F3D0", "3° FASCIA": "#BFDBFE", "4° FASCIA": "#C4B5FD", "5° FASCIA": "#FDBA74", "6° FASCIA": "#FDA4AF" };
const stateVersion = 2;
const legacyTierMap: Record<string, Tier> = { "FASCIA 1": "1° FASCIA", "FASCIA 2": "2° FASCIA", "3 SCELTE": "3° FASCIA", SICURO: "4° FASCIA", SCOMMESSA: "5° FASCIA" };
const normalizeTier = (value: string): Tier => legacyTierMap[value] ?? value as Tier;
const normalizeTierLabels = (stored?: Record<string, string>): Record<Tier, string> => { const next = { ...defaultTierLabels }; Object.entries(stored ?? {}).forEach(([key, label]) => { const normalized = legacyTierMap[key] ?? key; if (legacyTierMap[key] && label === key) return; if (normalized in next) next[normalized as Tier] = label; }); return next; };
const defaultStrategy: StrategySlot[] = Array.from({ length: 11 }, (_, index) => ({ id: index + 1, role: index < 3 ? "P" : index < 6 ? "D" : index < 9 ? "C" : "A", player: "", tier: "", budget: "" }));
type AuctionState = { totalCredits: number; slots: RosterSlots; purchases: Purchase[]; participants: string[]; players: ListPlayer[]; listoneMeta: ListoneMeta; tiers: Record<string, Tier>; tierLabels: Record<Tier, string>; tierColors: TierColors; strategy: StrategySlot[]; strategyBudgets: StrategyBudgets; setTotalCredits: (value: number) => void; setSlots: (value: RosterSlots) => void; setParticipants: (value: string[]) => void; setTier: (player: string, tier: Tier | undefined) => void; setTierLabels: (value: Record<Tier, string>) => void; setTierColors: (value: TierColors) => void; setStrategyBudgets: (value: StrategyBudgets | ((current: StrategyBudgets) => StrategyBudgets)) => void; setStrategy: (value: StrategySlot[]) => void; importListone: (players: ListPlayer[], meta: ListoneMeta) => void; addPurchase: (purchase: Purchase) => void; removePurchase: (player: string) => void };
const AuctionContext = createContext<AuctionState | null>(null);
export function AuctionProvider({ children }: { children: ReactNode }) {
  const [totalCredits, setTotalCreditsState] = useState(1000); const [slots, setSlotsState] = useState<RosterSlots>(defaultSlots); const [purchases, setPurchases] = useState<Purchase[]>([]); const [participants, setParticipantsState] = useState(defaultParticipants); const [players, setPlayers] = useState<ListPlayer[]>(defaultPlayers); const [listoneMeta, setListoneMeta] = useState<ListoneMeta>(defaultListoneMeta); const [tiers, setTiers] = useState<Record<string, Tier>>({}); const [tierLabels, setTierLabelsState] = useState(defaultTierLabels); const [tierColors, setTierColors] = useState<TierColors>(defaultTierColors); const [strategy, setStrategy] = useState(defaultStrategy); const [strategyBudgets, setStrategyBudgets] = useState<StrategyBudgets>(defaultStrategyBudgets); const [hydrated, setHydrated] = useState(false);
  useEffect(() => { AsyncStorage.getItem("fanta-asta-state").then((raw) => { if (!raw) { setHydrated(true); return; } try { const value = JSON.parse(raw); if (value.totalCredits) setTotalCreditsState(value.totalCredits); if (value.slots) setSlotsState(value.slots); if (value.purchases) setPurchases(value.purchases.map((item: Purchase) => ({ player: item.player, team: item.team, role: item.role, owner: item.owner ?? "", amount: item.amount ?? 0 }))); if (value.participants?.length) setParticipantsState(value.participants); if (value.players?.length) setPlayers(value.players); if (value.listoneMeta) setListoneMeta(value.listoneMeta); if (value.tiers) setTiers(Object.fromEntries(Object.entries(value.tiers).map(([player, tier]) => [player, normalizeTier(String(tier))])) as Record<string, Tier>); setTierLabelsState(value.stateVersion === stateVersion ? normalizeTierLabels(value.tierLabels) : defaultTierLabels); if (value.tierColors) setTierColors({ ...defaultTierColors, ...value.tierColors }); if (value.strategy) setStrategy(value.strategy.map((item: StrategySlot) => ({ ...item, tier: item.tier ? normalizeTier(item.tier) : "" }))); if (value.strategyBudgets) setStrategyBudgets({ ...defaultStrategyBudgets, ...value.strategyBudgets }); } catch { /* ignore invalid local state */ } finally { setHydrated(true); } }); }, []);
  useEffect(() => { if (!hydrated) return; AsyncStorage.setItem("fanta-asta-state", JSON.stringify({ stateVersion, totalCredits, slots, purchases, participants, players, listoneMeta, tiers, tierLabels, tierColors, strategy, strategyBudgets })); }, [hydrated, totalCredits, slots, purchases, participants, players, listoneMeta, tiers, tierLabels, tierColors, strategy, strategyBudgets]);
  const value = useMemo(() => ({ totalCredits, slots, purchases, participants, players, listoneMeta, tiers, tierLabels, tierColors, strategy, strategyBudgets, setTotalCredits: setTotalCreditsState, setSlots: setSlotsState, setParticipants: setParticipantsState, setTierLabels: setTierLabelsState, setTierColors, setStrategyBudgets, setStrategy, importListone: (nextPlayers: ListPlayer[], meta: ListoneMeta) => { const update = createListoneImportUpdate(nextPlayers, meta, strategy); setPlayers(update.players); setListoneMeta(update.listoneMeta); setPurchases(update.purchases); setTiers(update.tiers); }, setTier: (player: string, tier: Tier | undefined) => setTiers((current) => { const next = { ...current }; if (tier) next[player] = tier; else delete next[player]; return next; }), addPurchase: (purchase: Purchase) => setPurchases((current) => [...current.filter((item) => item.player !== purchase.player), purchase]), removePurchase: (player: string) => setPurchases((current) => current.filter((item) => item.player !== player)) }), [totalCredits, slots, purchases, participants, players, listoneMeta, tiers, tierLabels, tierColors, strategy, strategyBudgets]);
  return <AuctionContext.Provider value={value}>{children}</AuctionContext.Provider>;
}
export function useAuction() { const value = useContext(AuctionContext); if (!value) throw new Error("useAuction must be used inside AuctionProvider"); return value; }
