import { ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useAuction } from "@/lib/auction-context";
import { getTeamPurchaseSummary, sortPurchasesByRole } from "@/lib/auction-utils";
export default function AuctionScreen() {
  const { purchases, totalCredits, participants, slots, tiers, tierLabels, tierColors } = useAuction();
  const me = participants[0] ?? "Io";
  const mySummary = getTeamPurchaseSummary(purchases, me, totalCredits);
  return <ScreenContainer edges={["top", "left", "right"]} containerClassName="bg-background"><ScrollView contentContainerStyle={styles.screen}><Text style={styles.eyebrow}>STRATEGIA ASTA / RIEPILOGO</Text><Text style={styles.title}>Le rose.</Text><Text style={styles.subtitle}>Una scheda separata per ogni partecipante.</Text><Text style={styles.summaryOwner}>LA TUA SQUADRA · {me.toUpperCase()}</Text><View style={styles.summary}><View><Text style={styles.label}>SPESA</Text><Text style={styles.big}>{mySummary.spent}</Text><Text style={styles.muted}>crediti</Text></View><View><Text style={styles.label}>RESIDUI</Text><Text style={[styles.big, { color: "#D9F99D" }]}>{mySummary.remaining}</Text><Text style={styles.muted}>su {totalCredits}</Text></View><View><Text style={styles.label}>PRESI</Text><Text style={[styles.big, { color: "#FB923C" }]}>{mySummary.count}</Text><Text style={styles.muted}>calciatori</Text></View></View>{participants.map((person) => { const roster = sortPurchasesByRole(purchases.filter((item) => item.owner.toLowerCase() === person.toLowerCase())); const spentByPerson = roster.reduce((sum, item) => sum + item.amount, 0); const counts = roster.reduce((acc, item) => { acc[item.role] += 1; return acc; }, { P: 0, D: 0, C: 0, A: 0 } as Record<string, number>); return <View key={person} style={styles.personCard}><View style={styles.personTop}><View><Text style={styles.personName}>{person}</Text><Text style={styles.personMeta}>{roster.length} giocatori · {spentByPerson} crediti</Text></View><Text style={styles.personBudget}>{totalCredits - spentByPerson}</Text></View><View style={styles.roleCounts}>{(["P", "D", "C", "A"] as const).map((role) => <Text key={role} style={styles.roleCount}>{role} {counts[role]}/{slots[role]}</Text>)}</View>{roster.length > 0 ? roster.map((item) => <View key={item.player} style={styles.playerLine}><View style={styles.playerIdentity}><Text style={styles.player}>{item.player.toUpperCase()}</Text><Text style={styles.playerTeam}>{item.team.toUpperCase()}</Text>{tiers[item.player] && <Text style={[styles.playerTier, { color: tierColors[tiers[item.player]] }]}>{tierLabels[tiers[item.player]]}</Text>}</View><Text style={styles.amount}>{item.amount}</Text></View>) : <Text style={styles.emptyText}>Nessun giocatore assegnato</Text>}</View>; })}</ScrollView></ScreenContainer>;
}
  const styles = StyleSheet.create({ screen: { flexGrow: 1, backgroundColor: "#08111F", padding: 18 }, eyebrow: { color: "#8DA0B8", fontSize: 10, fontWeight: "800", letterSpacing: 1.7 }, title: { color: "#F7FAFC", fontSize: 37, lineHeight: 43, fontWeight: "900", marginTop: 7 }, subtitle: { color: "#9AAEC5", fontSize: 14, marginTop: 5, marginBottom: 22 }, summaryOwner: { color: "#75A7D9", fontSize: 9, fontWeight: "900", letterSpacing: 1.2, marginBottom: 8 }, summary: { flexDirection: "row", justifyContent: "space-between", backgroundColor: "#102238", borderWidth: 1, borderColor: "#1C3654", borderRadius: 18, padding: 17, marginBottom: 18 }, label: { color: "#75A7D9", fontSize: 9, fontWeight: "800", letterSpacing: 1.2 }, big: { color: "#FB923C", fontSize: 29, lineHeight: 34, fontWeight: "900", marginTop: 4 }, muted: { color: "#7F94AD", fontSize: 11 }, personCard: { backgroundColor: "#0E1C2F", borderWidth: 1, borderColor: "#284562", borderRadius: 17, padding: 16, marginBottom: 11 }, personTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, personName: { color: "#FB923C", fontSize: 19, fontWeight: "900" }, personMeta: { color: "#8EA4BE", fontSize: 11, marginTop: 4 }, personBudget: { color: "#D9F99D", fontSize: 22, fontWeight: "900" }, roleCounts: { flexDirection: "row", gap: 10, borderTopWidth: 1, borderBottomWidth: 1, borderColor: "#203A55", paddingVertical: 10, marginVertical: 12 }, roleCount: { color: "#A7B8CD", fontSize: 10, fontWeight: "800" }, playerLine: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 7 }, playerIdentity: { flex: 1, flexDirection: "row", alignItems: "baseline", flexWrap: "wrap", gap: 8 }, player: { color: "#EEF4FA", fontSize: 13, fontWeight: "800" }, playerTeam: { color: "#F87171", fontSize: 10, fontWeight: "900" }, playerTier: { color: "#8EA4BE", fontSize: 10, fontWeight: "600" }, amount: { color: "#D9F99D", fontSize: 14, fontWeight: "900" }, emptyText: { color: "#71869F", fontSize: 11, paddingTop: 3 } });
